### PR TITLE
Fix event base replication test

### PR DESCRIPTION
**Pull request by cesarempathy**
It should fix the test error 
https://github.com/BESTSELLER/terraform-provider-harbor/pull/64#issuecomment-773840379

### CODE REVIEW

**Review by wrighbr — COMMENTED** [review]
@cesarempathy in the doco 
https://registry.terraform.io/providers/BESTSELLER/harbor/latest/docs/resources/replication

action is required

**Review by wrighbr — APPROVED** [review]
OK LGTM

**Comment by wrighbr** [comment]
@cesarempathy I'm unable to merge you request because a merge conflict

**Comment by cesarempathy** [comment]
I have resolved the merge conflicts

**Pull request merged**
