### PR TITLE
Add cli secret

### PR DESCRIPTION
**Pull request by sj14**
Hello and thanks for you project.
I need to set the `cli_secret` and implemented what I think should work.
Unfortunately, I do no yet have a test setup with OIDC enabled for checking this.
I adjusted the tests in `provider/resource_user_test.go` but randomly changed stuff so that it *should* fail (not limited to the cli_secret), but my local tests still pass.

So, this is a first request for a review and maybe you already have a dev setup for testing this change.

Regards,
Simon

### CODE REVIEW

**Comment by wrighbr** [comment]
@sj14 what version of harbor are you using? 

This is resource was designed for local users and not OIDC users. 

from my understanding when oidc is configured users will be automatically added to the DB when users are signed. you can obtain the cli_serect using this doco.

https://goharbor.io/docs/1.10/administration/configure-authentication/oidc-auth/#:~:text=Using%20OIDC%20from%20the%20Docker%20or%20Helm%20CLI

**Comment by sj14** [comment]
We are using Version v2.1.3-b6de84c5. And you are right, the oicd users are automatically created when they login first. I guess I confused quite some stuff. So we probably have to set the cli_secret using another automation. Sorry for the noise.

**Comment by wrighbr** [comment]
no worries. If you looking for an automatic away of push/pull images to a repo take a look at the robot account resource

**Comment by sj14** [comment]
Thanks. We had checked them too but from an organizational aspect it doesn't seem to fit as we would need a new robot account for each project afaik. Our idea was to create a new user as a "robot account" and add them to the desired projects as a guest. Then we can handle all the pull/push with a single cli_secret.

**Comment by sj14** [comment]
@wrighbr I'm just thinking if an own `cli_secret` resource would be a solution. What do you think?

**Comment by wrighbr** [comment]
@sj14 I'm not sure how this would work. As once you have enabled OIDC you can't create a local account. This might be a feature request that goharbor needs to enable robot account access to multiple repos

**Comment by sj14** [comment]
Sorry, should have been more descriptive. The idea was to have something like

```
resource "harbor_users_cli_secret" "secret_john" {
  user_id = 1
  secret = "my_secret"
}
```

I would have to figure out if the user id is the oidc id or "local" id.

**Pull request closed without merging**
