### PR TITLE
Modify api path to add member to project

### PR DESCRIPTION
**Pull request by sshota0809**
This is related to #168 

I have modified api path to add member to project and also modified `provider.resourceMembersGroupCreate` because it depends on models.

Please review my PR!

### CODE REVIEW

**Comment by sshota0809** [comment]
SonarCloud Code Analysis was failed, but it seems that duplicated line is in a function between `resource_project_member_group.go` and `resource_project_member_user.go` that is not modified in this PR.

So I don't think it's problem.

**Comment by wrighbr** [comment]
@sshota0809 can you make sure the documentation is updated as well thanks

**Comment by sshota0809** [comment]
@wrighbr 

Due to this PR, resource_project_member_group` and `resource_project_member_user` should reference `harbor_project.xxxxx.project_id` instead of `xxxxx.main.id` and I have modified so as following commit.

https://github.com/BESTSELLER/terraform-provider-harbor/pull/172/commits/0d128aade3678dffb89a50a5cb9aceddd0249c83

I think nothing else isn't needed to be changed IN document.

**Review by wrighbr — APPROVED** [review]
LGTM

**Pull request merged**
