### PR TITLE
added "warning"

### PR DESCRIPTION
**Pull request by Gaardsholt**

### CODE REVIEW

**Review by wrighbr — APPROVED** [review]
LGTM

**Comment by Vad1mo** [comment]
@Gaardsholt @wrighbr, we should announce that in the Harbor community maybe someone is interested in taking over the project

**Comment by Gaardsholt** [comment]
@Vad1mo Brett did reach out to someone at Harbor to see if anybody wanted to take the ownership, but no one volunteered :(

**Comment by Vad1mo** [comment]
ok, I'll bring the attention to it again

**Comment by Gaardsholt** [comment]
Sure thing!
Would you have timeslot tomorrow?

**Pull request merged**
