### PR TITLE
Add event based option to replication policy

### PR DESCRIPTION
**Pull request by cesarempathy**
This give the possibility to create a `event based` replication policy and add the mapping for the destination namespace.

### CODE REVIEW

**Review by wrighbr — APPROVED** [review]
LGTM

**Comment by wrighbr** [comment]
@cesarempathy sorry after merging your request I your test failed
=== RUN   TestDestinationNamespace
    resource_replication_test.go:109: Step 1/1 error: Error running pre-apply refresh: 
        Error: Unsupported argument
        
          on config417152063/terraform_plugin_test.tf line 9, in resource "harbor_retention_policy" "main":
           9: 		  dest_namespace = "gcp-project"
        
        An argument named "dest_namespace" is not expected here.

**Comment by wrighbr** [comment]
@cesarempathy I've revert this pull request please fix your test and submit a new pull request

**Comment by flbla** [comment]
@wrighbr @cesarempathy can it be merged again?

**Comment by cesarempathy** [comment]
I think so I fixed the text in this pr 
https://github.com/BESTSELLER/terraform-provider-harbor/pull/67

**Comment by flbla** [comment]
@cesarempathy @wrighbr : in order to be merged again, I created a new branch from master and cherry-picked commits from this PR to it : https://github.com/BESTSELLER/terraform-provider-harbor/pull/76, is it OK for you?

**Pull request merged**
