### PR TITLE
Replace project_id in tfstate from <project number> to /projects/<project number>

### PR DESCRIPTION
**Pull request by sshota0809**
This PR is related to #175 .

I have replaced `project_id` param in tfstate from `<project number>` to `/projects/<project number>` because this is breaking change I don't intend. I also modified document.

### CODE REVIEW

**Comment by sshota0809** [comment]
ACC_test was timeout, but I have no clue. so force push and rerun it.

**Comment by wrighbr** [comment]
@mxmorin would you like to review this before merge the PR

**Review by wrighbr — APPROVED** [review]
LGTM

**Comment by mxmorin** [comment]
Tested with success. Breaking change has disappeared
Thanks

**Pull request merged**
